version: '3.7'
services:
  api-test-hub:
    container_name: api-test-hub
    build: .
    env_file:
      - .env.local
    ports:
      - 3000:3000
    volumes:
      - ./:/home/app/api-test-hub
      - /home/app/api-test-hub/node_modules
    links:
      - db_api_test
    depends_on:
      - db_api_test
    command: yarn start:dev

  db_api_test:
    container_name: db_api_test
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_test
    ports:
      - 5435:5432
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local